### ISSUE TITLE
群服互通名字为空问题

### ISSUE THREAD

**Issue by HDTianRu** [OmineDev/neomega-core#2]
刚刚发现群服互通有时候会出现没名字的情况，查了一下，当用户没设置群内名字时，msg.Sender.Card为空，这时候就要用msg.Sender.User.Nickname

也就是neomega_storage/config/cq_http_core.lua的156行该改为
sender_name = ((msg.Sender.Card ~= "" and msg.Sender.Card) or msg.Sender.User.Nickname) .. "#" .. msg.Sender.User.UserID

**Comment by Liliya233** [comment]
已修改
